
const { test, expect } = require('@playwright/test')
test('Drag nd Drop using inbuild commond', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    const rome = await page.locator('#box6')
    const Italy = await page.locator('#box106')
    await rome.dragTo(Italy)
    expect(await page.locator('#box6')).toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})

test('Drag nd Drop using mouse Actions-1', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box6').hover()
    await page.mouse.down()
    await page.locator('#box106').hover()
    await page.mouse.up()
    expect(await page.locator('#box6'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})


test('Drag and Drop using mouse Actions-2', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box7').hover()
    await page.mouse.down()
    await page.locator('#box107').hover()
    await page.mouse.up()
    expect(await page.locator('#box7'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})

test('Drag and Drop using mouse Actions-3', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box1').hover()
    await page.mouse.down()
    await page.locator('#box101').hover()
    await page.mouse.up()
    expect(await page.locator('#box1'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})

test('Drag and Drop using mouse Actions-4', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box2').hover()
    await page.mouse.down()
    await page.locator('#box102').hover()
    await page.mouse.up()
    expect(await page.locator('#box2'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})
test('Drag and Drop using mouse Actions-5', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box3').hover()
    await page.mouse.down()
    await page.locator('#box103').hover()
    await page.mouse.up()
    expect(await page.locator('#box3'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})

test('Drag and Drop using mouse Actions-6', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box4').hover()
    await page.mouse.down()
    await page.locator('#box104').hover()
    await page.mouse.up()
    expect(await page.locator('#box4'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})

test('Drag and Drop using mouse Actions-7', async ({ page }) => {
    await page.goto('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')
    await page.locator('#box5').hover()
    await page.mouse.down()
    await page.locator('#box105').hover()
    await page.mouse.up()
    expect(await page.locator('#box5'))
        .toHaveAttribute('style', 'visibility: visible; background-color: rgb(0, 255, 0);')
    await page.waitForTimeout(5000)
})
